export const lightTheme = {
  body: "var(--color-white)",
  text: "var(--color-black)",
  h2: "var(--color-white)",
  header: "var(--color-pink)",
  colors: {
    success: "var(--color-success)",
    white: "var(--color-white)",
    error: "var(--color-red)",
    text: "var(--color-black)",
  },
  // Buttons, links, and other UI elements
  viewProductButton: "var(--color-pink-light)",
  viewProductButtonHover: "var(--color-pink)",
  viewProductButtonHoverDark: "var(--color-pink-dark)",
  productCardShadow: "var(--card-shadow-light)",
  productCardBackground: "var(--color-white)",
  navLinkShadow: "var(--box-shadow-light)",
  productCardText: "var(--color-black)",
  priceTextDiscounted: "var(--color-white)",
  priceBgDiscounted: "var(--color-red)",
  priceBgNormal: "var(--color-price-normal)",
  priceTextNormal: "var(--color-black)",
  input: "var(--color-white)",
  inputText: "var(--color-black)",
  inputBorderColor: "var(--color-gray-light)",
  searchResultBackground: "var(--color-pink-xlight)",
  searchResultBackgroundHover: "var(--color-pink-hover)",
  searchResultText: "var(--color-black)",
  errorMessage: "var(--color-red)",
  successMessage: "var(--color-success)",
};

export const darkTheme = {
  body: "var(--color-gray-dark)",
  text: "var(--color-pink-lighter)",
  h2: "var(--color-pink-lighter)",
  header: "var(--color-pink-dark)",
  colors: {
    success: "var(--color-success-darkMode)",
    white: "var(--color-white)",
    error: "var(--color-red-light)",
    text: "var(--color-pink-lighter)",
  },
  // Buttons, links, and other UI elements
  viewProductButton: "var(--color-pink-dark)",
  viewProductButtonHover: "var(--color-pink)",
  viewProductButtonHoverDark: "var(--color-pink-dark)",
  productCardShadow: "var(--card-shadow-dark)",
  navLinkShadow: "var(--box-shadow-dark)",
  productCardText: "var(--color-pink-xlight)",
  priceBgDiscounted: "var(--color-white)",
  priceTextDiscounted: "var(--color-red)",
  priceBgNormal: "var(--color-price-normal)",
  priceTextNormal: "var(--color-black)",
  input: "var(--color-pink-xlight)",
  inputText: "var(--color-black)",
  inputBorderColor: "var(--color-pink-light)",
  searchResultBackground: "var(--color-gray-dark)",
  searchResultBackgroundHover: "var(--color-gray-dark-hover)",
  searchResultText: "var(--color-pink-xlight)",
  errorMessage: "var(--color-red-light)",
  successMessage: "var(--color-success-darkMode)",
};
