export const lightTheme = {
  body: "var(--color-white)",
  text: "var(--color-black)",
  h2: "var(--color-white)",
  header: "var(--color-pink)",
  // Buttons, links, and other UI elements
  viewProductButton: "var(--color-pink-light)",
  viewProductButtonHover: "var(--color-pink)",
  productCardShadow: "var(--card-shadow-light)",
  productCardBackground: "var(--color-white)",
  navLinkShadow: "var(--box-shadow-light)",
  productCardText: "var(--color-black)",
  priceTextDiscounted: "var(--color-white)",
  priceBgDiscounted: "var(--color-red)",
  priceBgNormal: "var(--color-price-normal)",
  priceTextNormal: "var(--color-black)",
  input: "var(--color-white)",
  inputText: "var(--color-black)",
  searchResultBackground: "var(--color-pink-xlight)",
};

export const darkTheme = {
  body: "var(--color-gray-dark)",
  text: "var(--color-pink-lighter)",
  h2: "var(--color-pink-lighter)",
  header: "var(--color-pink-dark)",
  // Buttons, links, and other UI elements
  viewProductButton: "var(--color-pink-dark)",
  viewProductButtonHover: "var(--color-pink)",
  productCardShadow: "var(--card-shadow-dark)",
  navLinkShadow: "var(--box-shadow-dark)",
  productCardText: "var(--color-pink-xlight)",
  priceBgDiscounted: "var(--color-white)",
  priceTextDiscounted: "var(--color-red)",
  priceBgNormal: "var(--color-price-normal)",
  priceTextNormal: "var(--color-black)",
  input: "var(--color-pink-xlight)",
  inputText: "var(--color-black)",
  searchResultBackground: "var(--color-gray-light)",
};
